run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - govet
    - gofmt

linters-settings:
  staticcheck:
    checks:
      - all
      - -SA1019  # Disable deprecation warnings (AWS SDK v1 is used by dependencies)

issues:
  exclude-rules:
    # Exclude AWS SDK v1 deprecation warnings - used by dependencies
    - linters:
        - staticcheck
      text: "aws-sdk-go is deprecated"

    # Exclude test files from some checks
    - path: _test\.go
      linters:
        - errcheck
